spring:
 profiles:
  active:
  - dev
---
server:
 port: 7001
spring:
 profiles: dev
 application:
  name: eureka
eureka:
  instance:
    hostname: eureka1.com
  client:
    fetch-registry: false
    register-with-eureka: false
    service-url:
      defaultZone: http://eureka2.com:7002/eureka/,http://eureka3.com:7003/eureka/ #指定其他服务器地址
  #server:
    #enable-self-preservation: false 注销eureka的自我保护机制
---
server:
 port: 7001
spring:
 profiles: test
 application:
  name: eureka
eureka:
  instance:
    hostname: eureka1.com
  client:
    fetch-registry: false
    register-with-eureka: false
    service-url:
      defaultZone: http://eureka2.com:7002/eureka/,http://eureka3.com:7003/eureka/ #指定其他服务器地址
  #server:
    #enable-self-preservation: false 注销eureka的自我保护机制